### PR TITLE
add docker compose

### PR DESCRIPTION
**Pull request by phil-flip**

### CODE REVIEW

**Comment by vanschelven** [comment]
As it stands I won't accept Pull Requests; Bugsink is free (as in beer) to use for certain things, but it's not open to contribution for all.

[Unfortunately GitHub hasn't provided an option to remove PRs from the list of tabs yet](https://github.com/orgs/community/discussions/8907)

**Comment by vanschelven** [comment]
For things like Docker-compose (and similar) I may very well open a separate repo "deployment examples" which _is_ in fact open source as well as open to contributions.

**Comment by phil-flip** [comment]
That's kind of unfortunate and not in the spirit of open source. If you keep that opinion tho, maybe adding a notice somewhere in the readme.md would be useful, so other users don't send time on improving the code.

**Comment by vanschelven** [comment]
> not in the spirit of open source

[Indeed](https://github.com/bugsink/bugsink/blob/main/LICENSE) :smile: 

I do understand that it's a bummer if you've already put work in it, though... I've tried to make it more clear at least if you click that "PR" button (which is admittedly too late)

> A separate repo for two extra files is a little excessive.

The repo would be a general "3rd party additions" repo

**Pull request closed without merging**
